// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWGngQUofi7z6QXE44SiAN3SfdDegSKqE',
    appId: '1:489235477653:web:2a27b931893b116a52579c',
    messagingSenderId: '489235477653',
    projectId: 'quickmeet-be146',
    authDomain: 'quickmeet-be146.firebaseapp.com',
    storageBucket: 'quickmeet-be146.appspot.com',
    measurementId: 'G-QN4VZEEJ8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZOFMf19jpryNr7B0ongdJ-Dwa6bKjumk',
    appId: '1:489235477653:android:9867742391678b7452579c',
    messagingSenderId: '489235477653',
    projectId: 'quickmeet-be146',
    storageBucket: 'quickmeet-be146.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZZKeyTSiwFztasEdO0eJ-DicYS6r3FMQ',
    appId: '1:489235477653:ios:e353d42be06c57bf52579c',
    messagingSenderId: '489235477653',
    projectId: 'quickmeet-be146',
    storageBucket: 'quickmeet-be146.appspot.com',
    androidClientId: '489235477653-4l41bhpiudlvq1bv7rn6pes9d5coegr5.apps.googleusercontent.com',
    iosClientId: '489235477653-m7j4t7966939c8akfidkk9glvmsn4917.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalQuickMeet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZZKeyTSiwFztasEdO0eJ-DicYS6r3FMQ',
    appId: '1:489235477653:ios:e353d42be06c57bf52579c',
    messagingSenderId: '489235477653',
    projectId: 'quickmeet-be146',
    storageBucket: 'quickmeet-be146.appspot.com',
    androidClientId: '489235477653-4l41bhpiudlvq1bv7rn6pes9d5coegr5.apps.googleusercontent.com',
    iosClientId: '489235477653-m7j4t7966939c8akfidkk9glvmsn4917.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalQuickMeet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWGngQUofi7z6QXE44SiAN3SfdDegSKqE',
    appId: '1:489235477653:web:e4d922392b279f3152579c',
    messagingSenderId: '489235477653',
    projectId: 'quickmeet-be146',
    authDomain: 'quickmeet-be146.firebaseapp.com',
    storageBucket: 'quickmeet-be146.appspot.com',
    measurementId: 'G-VKDGDMG8T6',
  );

}